---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Apache and PHP
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Enable Apache mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/
    copy: no

- name: Set permissions for WordPress files
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    recurse: yes

- name: Configure WordPress wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php

- name: Change Apache DocumentRoot to /var/www/wordpress
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: '^(\s*)DocumentRoot\s+/var/www/html'
    line: '    DocumentRoot /var/www/wordpress'
    backrefs: yes

- name: Restart Apache to apply DocumentRoot change
  service:
    name: apache2
    state: restarted


